### ISSUE TITLE
[ISSUE] Multi player Not working, server down

### ISSUE THREAD

**Issue by manti** [es/2048-multiplayer#2]
Looking forward to play mutil player 2048, Crazy game!

**Comment by es** [comment]
Server is up, should be working now.

**Comment by tbodt** [comment]
Server is now down again...

**Comment by es** [comment]
I've ceased work on the project and taken down the servers. Please see the [project state note in the README](https://github.com/es/2048-multiplayer#project-state).

**Comment by tbodt** [comment]
I would like to host it myself, how would I set up the server side in heroku?
