### ISSUE TITLE
Two winners?

### ISSUE THREAD

**Issue by rixx** [es/2048-multiplayer#5]
Just played a game where both players received a "You win" message. They didn't have the same amount of points either.

**Comment by rashfael** [comment]
I noticed that, when that bug happens, my board shows a losing screen for half a second, then switches to win.

**Comment by es** [comment]
@rashfael That actually helps a lot. I think I might know what the issue is!

**Comment by t3db0t** [comment]
For what it's worth:
![screen shot 2014-04-16 at 7 06 51 pm](https://cloud.githubusercontent.com/assets/203307/2726487/e85f9444-c5bb-11e3-81f9-3fc4caa21251.png)

**Comment by vanderlee** [comment]
Just (a few minutes ago) encountered the same issue:

![image](https://cloud.githubusercontent.com/assets/649240/3614325/7f5edd50-0dbf-11e4-969e-e9f34c2eaa5a.png)

Neither game is "locked", like in @virgildisgr4ce's screenshot. AFAICT there was nothing remakable about this particular game that could help you out (sorry).
